src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

It was writing the entire backing array even if the ByteBuffer only covered part of the array.

Correctly serialize ImmutableRoaringBitmap 

---

src/main/java/org/roaringbitmap/RoaringBitmap.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java

As I have a similar issue as #36 with requiring a lot of intersect counts and wishing to avoid the cost of allocation I implemented the basic andCardinality method.
The logic is shamelessly stolen from the and method. The only difference is that only an int is incremented instead of a new RoaringBitSet build as are the two test cases.

#36 add andCardinality method that does not modify input RoaringBitSet

---

src/main/java/org/roaringbitmap/ArrayContainer.java
src/main/java/org/roaringbitmap/BitmapContainer.java
src/main/java/org/roaringbitmap/Container.java
src/main/java/org/roaringbitmap/RoaringBitmap.java
src/main/java/org/roaringbitmap/RunContainer.java
src/main/java/org/roaringbitmap/Util.java
src/test/java/org/roaringbitmap/TestContainer.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Hi this is the code to do the andCardinality without materializing the Containers. Which should be even faster. Again my apologies for messing up the code formatting. Hope this is useful.Before pulling could you have a look at the test cases to see if they make sense. I pulled them out of the or tests and added all against all container tests. Reading from the comments I think it does  a decent job of covering most possibilities.

#36 andCardinality methods added to the Containers avoiding materialization

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

Simple fix.
Make flip() of ImmutableRoaringBitmap is consistent with those of MutableRoaringBitmap and RoaringBitmap.
This PR fix #61

fix bug in flip() of ImmutableRoaringBitmap

---

src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java

This naive_and() always returns empty set. This was fixed in the past for the mutable parameters method, but not the immutable parameters one.

fix for naive_and() method when using immutable parameters

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java

fixed: The container pointer wasn't advanced, and when adding an instance to a Map the application hanged.
The equals() method should also be implemented to be consistent with the hashCode(). I don't know exactly when two arrays should be considered equal ( checking every single byte might be too expensive, depending on how the arrays are used )

fixed bug on hashCode() method. It entered an infinite loop.

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java

org.roaringbitmap.buffer.ImmutableRoaringBitmap cannot be cast to org.roaringbitmap.buffer.MutableRoaringBitmap

fix: java.lang.ClassCastException

---

src/main/java/org/roaringbitmap/ArrayContainer.java
src/main/java/org/roaringbitmap/BitmapContainer.java

This pull request is focused on resolving occurrence of Sonar rule
squid:LowerCaseLongSuffixCheck - Long suffix "L" should be upper case.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:LowerCaseLongSuffixCheck
Please let me know if you have any questions.
George Kankava

squid:LowerCaseLongSuffixCheck - Long suffix "L" should be upper case

---

src/main/java/org/roaringbitmap/FastAggregation.java
src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java

This pull request is focused on resolving occurrences of Sonar rule
squid:S2293 - The diamond operator ("<>") should be used.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2293
Please let me know if you have any questions.
George Kankava

squid:S2293 - The diamond operator ("<>") should be used

---

src/main/java/org/roaringbitmap/BitmapContainer.java
src/main/java/org/roaringbitmap/RoaringArray.java
src/main/java/org/roaringbitmap/RunContainer.java

This pull request is focused on resolving occurrences of Sonar rule
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
George Kankava

squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

The bug was in selectRangeWithoutCopy. The real bug is in  MappeableArrayContainer.remove(begin.end) method when begin=end=0. It removed everything in the container. It worked for cases where begin != end.
I worked around this by not invoking remove if lbStart == 0. I added the same check for lbLast as well though I dint check the behavior of MappeableArrayContainer.remove when lbLast == BufferUtil.maxLowBitAsInteger()
Test cases pass now. I also added additional test for selectRangeWithoutCopy.

Fixing selectRangeWithoutCopy

---

jmh/run.sh
pom.xml
style/roaring_google_checks.xml

Hey,
can someone please verify, if the current master branch can not be built because of checkstyle violations? Because here it does:
``
$ mvn clean package -DskipTests -Dgpg.skip=true
`` 
It does so on do/while blocks, when the "while" statement is put on the same line as the curly bracket.
If this is wanted, then i fixed those violations.
I also added checks for "run.sh" in the jmh folder, so that it fails, whenever one of the "mvn" commands fails. Right now it always ran through and jmh used old deployed versions of the jars (grrrr, took me some time to figure out, that it failed bcs of checkstyle)

Checkstyle fixes

---

memory/run.sh

Using /usr/bin/env bash as suggested by the top SO answer:
http://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang

Add missing shebang to memory/run.sh

---

jmh/pom.xml
jmh/src/main/java/org/roaringbitmap/UtilBechmark.java
jmh/src/main/java/org/roaringbitmap/UtilBenchmark.java
src/main/java/org/roaringbitmap/Util.java

The aim of the commit is to verify optimal value for Util.unsignedIntersect2by2 parameter.
Currently it's is param=64
The commit contains first version of benchmarking the `galloping` and `local` algorithm variants.
For param={"10","15","20","25","30","35", "40", "50","60", "90"} it generates five different examples:
* small container S
* big contained B (B.length = param * S.size)
The container values are generated by Uniform Distribution in version1.
The examples are deterministic, random seed is hardcoded.

Fine tune array-array intersection algorithm #63

---

jmh/src/main/java/org/roaringbitmap/buffer/BufferUtilBenchmark.java
jmh/src/main/java/org/roaringbitmap/buffer/UtilBenchmark.java
src/main/java/org/roaringbitmap/buffer/BufferUtil.java

Seems like the optimal parameter for Buffer version is around 35-40.
Next step is to generate more examples and focus on 25-60 range.
I wonder why is there clear split between "uniform" preferring local and "clustered" preferring galloping

Tune MappeableArrayContainer intersection algorithm

---

src/main/java/org/roaringbitmap/FastAggregation.java
src/main/java/org/roaringbitmap/RoaringBitmap.java
src/test/java/org/roaringbitmap/TestFastAggregation.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Improved API for `RoaringBitmap` and `FastAggregation` using wildcards for Iterator and List, as discussed in [Issue 145](https://github.com/RoaringBitmap/RoaringBitmap/issues/145).
Note that one method was not updated: `RoaringBitmap#and(Iterator)` as it was using old iterators - my guess being for compatibility reasons.
Cheers

Using wildcards

---

src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

In rare cases calling .rank() method on a run container returns a value that's off by one.
The provided test case reproduces the issue.
I include a proposed fix.

Fix MappeableRunContainer rank computation

---

jmh/src/main/java/org/roaringbitmap/realdata/RealDataBenchmarkIOr.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/Bitmap.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/ConciseSetWrapper.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/Ewah32BitmapWrapper.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/EwahBitmapWrapper.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/ImmutableConciseSetWrapper.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/ImmutableRoaringBitmapWrapper.java
jmh/src/main/java/org/roaringbitmap/realdata/wrapper/RoaringBitmapWrapper.java
jmh/src/test/java/org/roaringbitmap/realdata/RealDataBenchmarkIOrTest.java
src/main/java/org/roaringbitmap/ArrayContainer.java
src/main/java/org/roaringbitmap/Util.java
src/main/java/org/roaringbitmap/buffer/BufferUtil.java
src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java

I stumbled on this operator while working on my personal dataset. The proposed changes simply leverage an optimization that has been used before: if the backed array is large enough to hold the result and its initial content, push the content at the end of the array and write the result at the beginning. 
With less pressure on the garbage collector, I noticed a ~20% improvement in my usecase.
To validate the changes, I added a benchmark on our real dataset. See below the results. There is always either a speedup or no significant regression.
| Benchmark                        | (dataset)              | (immutable) | (type)           | Score before | Score after | Variation |
|----------------------------------|------------------------|-------------|------------------|--------------|------- …

Optimize ArrayContainer.ior(ArrayContainer)

---

src/main/java/org/roaringbitmap/RoaringBitmap.java
src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

The issue is addressed in the buffer package too.

rank of RoaringBitmap produces incorrect result #158

---

README.md
src/main/java/org/roaringbitmap/RoaringBitmap.java
src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

I was trying to confirm what is expected behaviour of bitmaps with negatives values. 
From the tests it was obvious that arguments are teated as UNSIGNED_INT.
Later I found it nicely documented in README but it would be great to have it documented it in javadoc.

Negative values documented

---

src/main/java/org/roaringbitmap/RunContainer.java
src/test/java/org/roaringbitmap/TestRunContainer.java

This fixes a bug where the first value would be returned as a negative
number when the start of the run used all 16 bits.

Handle signedness correctly in RunContainer.first

---

roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

This fixes a bug I encountered recently in equals between a RunContainer and an ArrayContainer whenever there is a run covering more than 15 bits.

fix unsigned equals bug in runcontainer

---

jmh/pom.xml
memory/pom.xml
pom.xml
real-roaring-dataset/pom.xml
roaringbitmap/pom.xml

Hello all,
I can offer you the following changes to support back the old release process.
It added a new profile `release` that deactivates tests for _jmh_, _memory_ and _real-data-set_, although I am not sure it we should deactivate the last.
The profile is automatically activated by the configuration of maven-release-plugin.
And it also restores the old release tag name.
I did not tested the full release process, only to `release:prepare`, not to commit the real files.
I let you decide how you want to ensure it works completely.
By the way, you can reduce your command by using the following `mvn release:clean release:prepare release:perform`.
Final note: I could have added another profile for the perform phase not to run again the tests. But as you did not mention it, I assume it was …

Correct release process

---

roaringbitmap/src/main/java/org/roaringbitmap/FastRankRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap_FastRank.java

Hello,
This PR follow-up https://github.com/RoaringBitmap/RoaringBitmap/issues/191
The general idea is to cache cardinalities, cumulated through buckets. This yield better performance when doing a lot of .rank and .select operations over a RoaringBitmap which is not written anymore.
Raw performance results (see TestRoaringBitmap_FastRank):
AddOnlyThenSelectOnly FastRankRoaringBitmap=207ms
AddOnlyThenSelectOnly RoaringBitmap=6064ms
AddSelectRemoveAreMixed FastRankRoaringBitmap=1055ms
AddSelectRemoveAreMixed RoaringBitmap=375ms
I am not fully-convinced `FastRankRoaringBitmap` is a proper naming for this class

Faster .rank .select

---

jmh/src/main/java/org/roaringbitmap/writer/WriteSequential.java
jmh/src/main/java/org/roaringbitmap/writer/WriteUnordered.java
roaringbitmap/src/main/java/org/roaringbitmap/OrderedWriter.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/Util.java
roaringbitmap/src/test/java/org/roaringbitmap/OrderedWriterRandomisedTest.java
roaringbitmap/src/test/java/org/roaringbitmap/TestOrderedWriter.java
roaringbitmap/src/test/java/org/roaringbitmap/TestUtil.java
roaringbitmap/src/test/java/org/roaringbitmap/UnorderedWriterRandomisedTest.java

This pull request makes it possible to write sequentially and incrementally to a RoaringBitmap efficiently, without collecting values in an `int[]` beforehand. 
**Usage**
`OrderedWriter` wraps a `RoaringBitmap` and requires the caller to flush it to ensure all added data is saved to the bitmap.
```
OrderedWriter writer = new OrderedWriter(rb);
// add data incrementally, the most signficant 16 bits must be in ascending unsigned order
for (int i : values) {
writer.add(i);
}
// flush all buffered data down to the underlying bitmap
writer.flush();
```
**Testing**
The basic behaviour of `OrderedWriter` is tested in `TestOrderedWriter`.
That a RoaringBitmap built by an `OrderedWriter` is equivalent to one built by `RoaringBitmap.bitmapOf` is tested for random bitmaps of various size in …

Speed up incremental sequential writes and batch creation from unsorted data

---

jmh/run.sh

In this PR I introduce a couple of changes jmh/run.sh:
* running the `clean` Maven target is now optional. Explicitly pass `-clean` as the first argument to revert to old behavior. This cuts down on tool start time.
* skip check style. I don't think there is a point in having checkstyle run for this tool.
* add ability to pass an arbitrary number of arguments to JMH. This allow for easier passing of JMH parameters, like `-p dataset=dimension_003`

Changes to jmh/run.sh

---

roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java

This fixes a bug in RunContainer.contains(RunContainer) (this was my own handiwork unfortunately) which you would need a truncation of an identical run container to reproduce.

fix unsigned error in runcontainer contains runcontainer

---

jmh/src/main/java/org/roaringbitmap/RoaringOnlyBenchmarkState.java
jmh/src/main/java/org/roaringbitmap/realdata/state/RealDataRoaringOnlyBenchmarkState.java
jmh/src/main/java/org/roaringbitmap/runcontainer/ArrayContainerAndNotRunContainerBenchmark.java
jmh/src/main/java/org/roaringbitmap/runcontainer/BasicAndNotContainerBenchmark.java
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Util.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestUtil.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestUtil.java

I've decided to try using `Util.advanceUntil` in `andNot` between `ArrayContainer` and `RunContainer`. The implementation present in the commit was verified with present tests and a new one, but for sure I'd test it more if going to be merged.
I run two benchmarks `part{3,4}_andNotArrayContainerVSRunContainerContainer` on `master` and the new branch.
```
BasicAndNotContainerBenchmark.part3_andNotArrayContainerVSRunContainerContainer  avgt   15  3327,444 ± 49,353  ns/op
BasicAndNotContainerBenchmark.part4_andNotArrayContainerVSRunContainerContainer  avgt   15  1877,370 ± 25,888  ns/op
BasicAndNotContainerBenchmark.part3_andNotArrayContainerVSRunContainerContainer  avgt   15  7790,214 ± 81,502  ns/op
BasicAndNotContainerBenchmark.part4_andNotArrayContainerVSRunContainerContainer  avgt   15 …
```

AC.andNot(RC)

---

jmh/src/main/java/org/roaringbitmap/BasicBenchmark.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

The code from benchmark is standard way in my codebase to create big bitmap representing the `Universe`, which is later it is used for negations.
The code creating `rangeOfOnes` was using the `iadd` code which is too complicated for this simple case. Instead I've switched to constructors including new one for `RunContainer`
The speed improvement is from `8k ops/s` to `12k ops/s` for standard bitmaps and `7.7k ops/s` to `10.5k ops/s` for `buffered`.

Bitmap add range performance

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

The RoaringArray's `keys` and `values` arrays are extended with some extra space according to [code](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/RoaringArray.java#L320).
The space is not recovered after `RoaringBitmap.trim()` call. This could cause huge heap usage while building millions of bitmaps.
The unit tests shows how to easily waste `5292 bytes` per one bitmap.

Trim() is not releasing all unused bytes

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

For `RunContainers` the test fails with
```
org.junit.ComparisonFailure: 
Expected :{0,1,17,32767,-3,-1}
Actual   :{0,17,32767,65533,65535}
```
as the `toString()` for `RC` returns `[0,1][17,17][32767,32767][65533,65533][65535,65535]`
This was very misleading for me during my first pull requests.
The purpose of this PR is to decide what is the correct convention of `toString()` method or argumentation why there should be an exception.

.toString method inconsistent between containers

---

roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java

I have found that if calling code "knows" about runs, it's much easier to make the code as fast as possible. I imagine there will be some pushback on this. This is a small, low risk change, but might evoke strong feelings from a software engineering point of view.

make getLength and getValue public

---

jmh/src/main/java/org/roaringbitmap/realdata/ParallelAggregatorBenchmark.java
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/ParallelAggregation.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferParallelAggregation.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/ParallelAggregationTest.java
roaringbitmap/src/test/java/org/roaringbitmap/RandomisedTestData.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringArrayTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferFuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferParallelAggregationTest.java

This PR provides a way to execute arbitrary boolean reductions on bitmaps in parallel. 
Parallel `AND` and `ANDNOT` were implemented but found to be unprofitable. They can be implemented as circuits if necessary.

Implement parallel OR and XOR

---

jmh/src/main/java/org/roaringbitmap/iteration/BitmapIteratorBenchmark.java
jmh/src/main/java/org/roaringbitmap/iteration/IteratorsBenchmark32.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Util.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferBitSetUtil.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

I aim to speed container iteration up. Before doing that I did some instruction profiling, which revealed some suboptimal instructions were being JIT compiled for bitmap iteration:
```java
long t = bitset & -bitset;
array[pos++] = (short) (base + Long.bitCount(t - 1));
bitset ^= t;
```
```asm
0.89%    0x0000000004b27296: blsi    rbx,r10           
0.93%    0x0000000004b2729b: mov     rdi,rbx
2.22%    0x0000000004b2729e: xor     rdi,r10           
1.40%    0x0000000004b272a1: mov     qword ptr [r11+10h],rdi  
2.22%    0x0000000004b272a5: mov     ecx,r8d
0.57%    0x0000000004b272a8: shl     ecx,6h
2.06%    0x0000000004b272ab: dec     rbx
1.24%    0x0000000004b272ae: popcnt  rbx,rbx
2.25%    0x0000000004b272b3: add     ecx,ebx           
```
Iterating over a bitmap of various densities looks …

Better use of bit manipulation instructions for bitmap iterations

---

AUTHORS
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java

**In case when we increased capacity, we used to follow below steps:**
1. increaseCapacity(Arrays.copyOf)   - Copy 1st time
2. System.arrayCopy to offset  - Copy 2nd time
3. Perform Union
**With changes, it saves 2 copies:**
1. - create new array. (No copy)
2. - Perform union with new array as destination

Fix to avoid double copy in in-place array OR

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/RandomisedTestData.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapIntervalIntersectionTest.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferFuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/RoaringBitmapIntervalIntersectionTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

implement contains range

---

jmh/src/main/java/org/roaringbitmap/RandomData.java
jmh/src/main/java/org/roaringbitmap/iteration/BatchIteratorBenchmark.java
jmh/src/main/java/org/roaringbitmap/iteration/IteratorsBenchmark32.java
roaringbitmap/src/main/java/org/roaringbitmap/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/ContainerBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RunBatchIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/ContainerBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/RandomisedTestData.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferContainerBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

Sorry, I had to erase the last branch because of some of the commits. This is the same code, complete with the buffer implementation. I'm still keen to get some help benchmarking it.

implement batch iterators

---

jmh/src/main/java/org/roaringbitmap/range/ContainsRange.java

This adds a quick benchmark for contains range queries

add contains range benchmark

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java

This implements similar functionality to `java.util.BitSet.nextSetBit`, except the next bit is returned as a long, since RoaringBitmaps can contain all 32 bits.

implement nextSetBit

---

roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java

Legal-Meta - I didn't notice I didn't have sign-off set when I committed the change  to the test case, but by signing off on the substantive fix, and by submitting this pull request, it is my express intent to grant any and all rights necessary to incorporate these changes into the existing codebase, and that I am legally entitled to grant such rights under the laws of the United States of America and the State of North Carolina.
/s/ Simon Spero

Tests and fix for issue #254 (RunContainer.contains(ArrayContainer))

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java

There are a few opportunities to reduce duplication between the `Container::contains(Container)` methods and `Container.contains(int min, int sup)` methods, and this fixes some errors where signed values should be treated as unsigned. 
These changes have been made specifically to avoid any merge conflicts with #255.

simplify and fix signedness issues in contains methods

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/FastRankRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/PeekableIntRankIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/PeekableShortRankIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRankIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRankIteratorsOfContainers.java

Follow-up #191/#192.
Current FastRankRoaringBitmap implementation holds a cache of containers’ cardinalities and drastically improves rank calculation in case of random access.
I propose an enhancement for sequential access case — next/advanceIfNeed followed by obtaining rank of found position.
My original case is a very sparse column implemented as bitmap and array using rank as non-empty value position.
Another example (cc #72): two sparse vectors can be implemented as bitmap-array pair and dot product of them can be calculated by intersection via advanceIfNeed and extracting values using match ranks.
I have to make a separate family of rank iterators because rank processing will reduce performance for classical usecases (except of ArrayContainerShortIterator -- getting it's sub-rank is …

Fast rank-peekable iterators

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Adds `RoaringBitmap.addN` method, to allow adding multiple values to RoaringBitmap while respecting some boundaries.
This is useful when the user wants to reuse large preallocated `int[]` instances to create multiple RoaringBitmaps. Without it, the user needs to create array copies: `roaringBitmap.add(Arrays.copyOf(arr, len))`

Add RoaringBitmap.add with offset and length arguments

---

roaringbitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
roaringbitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

The issue was precisely that signedLong was not used to adjust the NavigableMap ordering during deserialization

Fix NavigableMap ordering during deserialization

---

roaringbitmap/src/main/java/org/roaringbitmap/insights/BitmapAnalyser.java
roaringbitmap/src/main/java/org/roaringbitmap/insights/BitmapStatistics.java
roaringbitmap/src/main/java/org/roaringbitmap/insights/NaiveWriterRecommender.java
roaringbitmap/src/test/java/org/roaringbitmap/RandomisedTestData.java
roaringbitmap/src/test/java/org/roaringbitmap/insights/BitmapAnalyserTest.java
roaringbitmap/src/test/java/org/roaringbitmap/insights/BitmapStatisticsTest.java
roaringbitmap/src/test/java/org/roaringbitmap/insights/NaiveWriterRecommenderTest.java

The method to gather statistics on internal representation of bitmap or bitmaps. 
They best express things like total count of containers and average capacity, so they may lead to false conclusions.
The statistics are used by naive version of Writer recommender.
I'd definitely need something like this for my bitmap builders use cases.

Bitmap statistics & naive writer heuristics recommendation

---

fuzz-tests/pom.xml
pom.xml

Fixes issue using artifacts built with jdk 9+ when run on java 8, which produces errors of the form:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
at org.roaringbitmap.buffer.ImmutableRoaringArray.<init>(ImmutableRoaringArray.java:51)
at org.roaringbitmap.buffer.ImmutableRoaringBitmap.<init>(ImmutableRoaringBitmap.java:968)
...
```
This is due to changes to several `ByteBuffer` methods in java 9+ resulting in bytecode generated that includes mismatched return types when built with jdk 9 or newer, [as described in this issue](https://jira.mongodb.org/browse/JAVA-2559).
This PR fixes this issue by adding the `release` compiler flag, described in [JEP 247](http://openjdk.java.net/jeps/247). This is done by adding an additional maven profile that activates …

Fix Java 8 compatibility issue

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/FastRankRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/PeekableShortRankIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRankIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRankIteratorsOfContainers.java

Unfortunately, I was introduced a very stupid bug in #263 for rank iterators.
Rank range is 1-65536, not 0-65535, so a short overflow happens for full containers.
There is a fix w/ regression tests.

Rank iterator short overflow bugfix

---

fuzz-tests/pom.xml
pom.xml

Since #290 dropped support for building with jdk8, the first version of #288 is a simpler setup since we can drop the extra profile. Tested locally that built artifact still functions with java 8.

simplify pom since jdk8 build support dropped

---

jmh/src/main/java/org/roaringbitmap/iteration/BatchIteratorBenchmark.java
roaringbitmap/src/main/java/org/roaringbitmap/BatchIntIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BatchIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

Sorry I meant to push this earlier. Reusing the buffer makes quite a big difference in preventing the TLAB filling up.

externalise buffer to allow reuse

---

roaringbitmap/src/main/java/org/roaringbitmap/ContainerAppender.java

This is a micro-optimisation (not reassigning a reference to itself, avoiding GC book-keeping code) which can make quite a big difference with G1. Here are some results (contrived so that container transitions actually happen, using G1 and a 4G heap) with the check:
```
Benchmark                                    (randomness)  (scenario)    (size)  Mode  Cnt      Score      Error  Units
WriteSequential.incrementalUseOrderedWriter           0.1      SPARSE    100000  avgt    5    626.854 ±    5.466  us/op
WriteSequential.incrementalUseOrderedWriter           0.1      SPARSE   1000000  avgt    5   5883.839 ±   12.712  us/op
WriteSequential.incrementalUseOrderedWriter           0.1      SPARSE  10000000  avgt    5  59593.382 ± 4854.011  us/op
WriteSequential.incrementalUseOrderedWriter …
```

avoid potentially costly write barrier

---

roaringbitmap/src/main/java/org/roaringbitmap/BatchIntIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

I introduced a bug in `BatchIntIterator`, this fixes it.

fix termination condition bug in BatchIntIterator

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringArrayTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/MutableRoaringArrayTest.java

Fixes a case where keys get reallocated if they have already been sized precisely + reproducing test case.

avoid resizing keys when keys are already at optimal size

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java

This optimises adding to arrays for append only scenarios. This will significantly speed up this case because it avoids a costly binary search, the branch is predictable, the other side of the branch will probably not even get compiled if it is never profiled. This will probably add the cost of an unpredicatable branch to random adds, but these are likely very slow anyway, and I think the penalty is likely worth it. I don't have much time to benchmark this but am receptive to opposition on the wisdom of this optimisation.

optimise array add for append-only

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/test/java/org/roaringbitmap/TestSerializationViaByteBuffer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestSerializationViaByteBuffer.java

Fixes a bug when serialising a bitmap to a big endian buffer with a non zero position + reproducing unit test.

fix bug when serialising many bitmaps to same file

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/ContainerBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RunBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RunBatchIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/DirectoryCleanup.java
roaringbitmap/src/test/java/org/roaringbitmap/TestSerializationViaByteBuffer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestSerializationViaByteBuffer.java

Reduces allocation of batch iterators to a constant 40-120 bytes, depending on the number of container types which exist in the bitmap, down from potentially tens or hundreds of kilobytes depending on the size of the bitmap. Otherwise negligible impact on performance.

flyweight container batch iterators

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Two bugs were addressed:
* In method RoaringBitMap.intersects(long minimum, long supremum), the starting position used to lookup into the last container was always forced to zero whereas it should not be the case if the minimum and supremum are in the same container.
* The intersection detection in the runContainer between the range (minimum, supremum) and the various runs in the container was wrong: In fact, [a, b] and [c, d] intersect if a <= d && c <=b

Fix intersection between Roaring BitMap and range (#333)

---

README.md

The license formerly known as "Apache Software License" (ASL) is now called the "Apache License" (AL).

Replace "ASL" with "AL".

---

README.md

Druid is an Apache project now, so I renamed "Druid" to "Apache Druid" and pointed the website at https://druid.apache.org/.

Druid is now Apache Druid

---

README.md
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

The implementation is simpler and relies on binary searches repeatedly (for simplicity)
so the performance should be lower than the previous implementation.
Note that we preserve the cardinality, so the offset can wrap values around.
This would fix https://github.com/RoaringBitmap/RoaringBitmap/issues/331

We can now use the "addOffset" function with negative offsets.

---

jmh/build.gradle.kts

reverts a couple of minor regressions to the build.

make sure benchmarks jar is multi release and named properly

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmapWriter.java

It looks like building an appender captures its a member variable from its builder.

stop ContainerAppender from capturing its builder

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java

LGTM complains about our inconsistent use of hashCode and equals. This should not affect end users but is maybe worth fixing nevertheless.

Attempt to fix "errors" identified by LGTM.

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
jmh/src/jmh/java/org/roaringbitmap/RandomData.java
jmh/src/jmh/java/org/roaringbitmap/combinedcardinality/CombinedCardinalityBenchmark.java

Avoids passing over the containers twice in `RoaringBitmap.andNotCardinality` resulting in a speed up
```
Benchmark                                                (scenario)  Mode  Cnt      Score    Error  Units
CombinedCardinalityBenchmark.andNotCardinality                EQUAL  avgt    5  12824.490 ± 46.868  us/op
CombinedCardinalityBenchmark.andNotCardinality              SHIFTED  avgt    5   1436.731 ± 31.097  us/op
CombinedCardinalityBenchmark.andNotCardinality          SMALL_LARGE  avgt    5      0.823 ±  0.038  us/op
CombinedCardinalityBenchmark.andNotCardinality          LARGE_SMALL  avgt    5     78.883 ±  0.606  us/op
CombinedCardinalityBenchmark.andNotCardinalityBaseline        EQUAL  avgt    5  12746.360 ± 66.701  us/op
CombinedCardinalityBenchmark.andNotCardinalityBaseline …
```

add specialised andNotCardinality for improved performance

---

.travis.yml
README.md

Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/382
Hopefully, Richard will like this better.

Fixing 382 by documentation.

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
jmh/build.gradle.kts

- change `RunContainer.intersects(BitmapContainer)` to check if the bitmap intersects with the range
- change `RunContainer.andCardinality(BitmapContainer)` to add the cardinality in the range of the run
- some miscellaneous test coverage enhancements

Runcontainer efficiency

---

jmh/src/jmh/java/org/roaringbitmap/aggregation/FastAggregationRLEStressTest.java

To reproduce #404 use: 
```
java -jar jmh/build/libs/benchmarks.jar -wi 5 -i 5 -r 1 -w 1 -f 1 -p count=100 FastAggregationRLEStressTest.andBuffer
```
Note that the array version is much faster, so the 18% just after the bounds check in the profile I posted on the issue might have something to do with it :):
```
Benchmark                               (constructionStrategy)  (count)  (probability)  (seed)   (size)   Mode  Cnt    Score    Error  Units
FastAggregationRLEStressTest.and               CONSTANT_MEMORY      100           0.01   99999  1000000  thrpt    5  216.592 ▒ 17.550  ops/s
FastAggregationRLEStressTest.and               CONSTANT_MEMORY      100            0.1   99999  1000000  thrpt    5   40.412 ▒  0.832  ops/s
FastAggregationRLEStressTest.and               CONSTANT_MEMORY …
```

benchmark for slow buffer run vs run and

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/Util.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/PointableRoaringArray.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestFastAggregation.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestFastAggregation.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestUtil.java
fuzz-tests/src/test/java/org/roaringbitmap/BufferFuzzer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java
jmh/src/jmh/java/org/roaringbitmap/realdata/ParallelAggregatorBenchmark.java

@lemire here's an intersection algorithm based on grouping by key and eliminating keys not associated with N containers in an N way intersection. Also avoids allocation by intersecting with a constant bitmap which is reused. Probably very buggy (PR is to offload running the tests), but quite fast:
new
```
FastAggregationRLEStressTest.and                                       CONTAINER_APPENDER      100           0.01   99999  1000000  thrpt    5     548.451 ▒      12.176   ops/s
FastAggregationRLEStressTest.and:▒gc.alloc.rate                        CONTAINER_APPENDER      100           0.01   99999  1000000  thrpt    5      15.309 ▒       0.344  MB/sec
FastAggregationRLEStressTest.and                                       CONTAINER_APPENDER      100            0.1   99999  1000000  thrpt …
```

implement new bitmap intersection algorithm

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/ImmutableLongBitmapDataProvider.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestStreams.java

methods that provide Int/LongStream() for streaming the index of set bits in Roaring(64)Bitmaps.
Sadly I needed to provide a wrapper class to transform a IntIterator into a PrimitiveIterator.OfInt (same for long).
IntIterator does not match the API signature of OfInt and changing that would be a backwards compatible issue.
I think I set the SplitIterator characteristics correctly, but a review of those would be appreciated.
Also the test cases copy shamelessly from the Iterator ones.

Issue#426 Add stream() and reverseStream() 

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/ImmutableLongBitmapDataProvider.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestStreams.java

This is a copy of  @JervenBolleman PR.
Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/426

Issue#426 Add stream() and reverseStream() methods that provide Int/LongStream() for streaming the index of set bits in Roaring(64)Bitmaps. (#427)

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node256.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node48.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node16Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node256Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node48Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node4Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

fix [issue](https://github.com/RoaringBitmap/RoaringBitmap/issues/428).  When iterating operations interwove with the removing ones it will make the `AbstractShuttle`'s stack hold a node's stale position data. This PR's main change is to let the stack to hold the node's fresh position data.
@lemire it's ready to give a review now.

fix issues when iterating the ART interwove with removing operations

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestEmptyRoaringBatchIterator.java

When the bitmap is empty, directly call the RoaringBatchIterator#nextBatch will throw NPE. We can skip it by return zero if the bitmap is empty.

fix empty RoaringBatchIterator#nextBatch NPE

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java

This PR fix one potential bug of `Node16` which is the same as `Node4`. Another potential bug is about to reverse iterating the `Roaring64Bitmap` .

some trivial fixes

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Since int is smaller than long, an int should always map to a positive
number in a long, that is, converting an int to a long should produce
a long in the range of [0, 2^32]. Since addInt directly calls addLong
without doing a proper conversion, the negative sign is being carried
over and setting incorrect positions in the map. For example,
addInt(-1) should be equivilant to addLong(((int) -1) & 0xffffffffL),
but its not. This patch fixes the issue by converting an int to
an unsigned long before calling addLong.

Roaring64Bitmap::addInt Setting Wrong Bits

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

This patch fixes a bug where Roaring64Bitmap will accept an invalid
range without failing and produce an incorrect bitmap. Since the range
is [inclusive, exclusive) adjusting the right end point by subtracting
one from it can create a bigger range. For example, bitmap.add(0, 0)
is an invalid range, but it will produce a bitmap with all positions
set to 1.

Validate Add Range

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Containers.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Since Roaring64Bitmap only adds to the ART and never removes a
prefix even if the lowpart container is empty, the tree leak memory,
even when empty. This patch will remove the high part from the
HighLowContainer when the lowpart container is empty after
a removeLong operation.
Also, this highpart leak can lead to incorrect results when
checking for logical equality.

Roaring64Bitmap Memory Leak

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java

There is no need to cast the bitmap to either RoaringBitmap or MutableRoaringBitmap, since `add(long,long)` was added to BitmapDataProvider
in v0.7.22 https://github.com/RoaringBitmap/RoaringBitmap/commit/e21398ed25e38c54dcb351413d0f8fde42398f15#diff-2845c9ffc4aff5c1702093d822944f8a67d47d4b61e2ef2865a1d2405f60a6fcR24

Use BitmapDataProvider.add in Roaring64NavigableMap.add

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

This patch removes the key(high part) from highToBitmap when
the corresponding BitmapDataProvider becomes empty after a
removeLong call. This prevent memory leaks and fixes the equality
check when some mappings are empty but not removed from the map.

Roaring64NavigableMap equals Bug + Leak

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmapPrivate.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmapPrivate.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java
jmh/src/jmh/java/org/roaringbitmap/aggregation/or/RoaringBitmapBenchmark.java

Based on [pr](https://github.com/RoaringBitmap/RoaringBitmap/pull/416) of @baibaichen, I add ut and benchmark.
and Roaring64NavigableMap's lazyor call RoaringBitmap#naivelazyor to accelerate,  so I just add benchmark for the comparison between RoaringBitmap's or method and RoaringBitmap's  lazyor method
The result of benchmark:
Benchmark                      (bitmapSize)  Mode  Cnt        Score        Error  Units
RoaringBitmapBenchmark.lazyor            10  avgt    5   140801.978 ±  13538.443  us/op
RoaringBitmapBenchmark.lazyor            50  avgt    5  1002109.229 ± 252619.378  us/op
RoaringBitmapBenchmark.lazyor           100  avgt    5  1374633.000 ±  82727.392  us/op
RoaringBitmapBenchmark.or                10  avgt    5   166109.292 ±  10970.728  us/op
RoaringBitmapBenchmark.or …

FastAggregation for Roaring64NavigableMap

---

RoaringBitmap/src/main/java/org/roaringbitmap/Util.java

Basically  we avoid two array copies in partialRadixSort and add a fast path for when the data is already sorted. See https://github.com/RoaringBitmap/RoaringBitmap/issues/470 Credit to @Ignition

Optimizations related to issue 470

---

RoaringBitmap/src/main/java/org/roaringbitmap/Util.java

This new code is simpler and seems to match (or even outmatch) competitors in https://github.com/RoaringBitmap/RoaringBitmap/issues/472
The proposed mechanism is that we make it easier for the compiler to lift bound checking. We also skip a buffer reinitialization.
Credit to @Ignition

Simplifying and speeding up partialRadixSort

---

RoaringBitmap/src/main/java/org/roaringbitmap/Util.java
RoaringBitmap/src/test/java/org/roaringbitmap/KryoTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestUtil.java
jmh/src/jmh/java/org/roaringbitmap/RadixSort.java

Since we're beating up on my 3 year old radix sort, here's another variant which has two benefits
1. Reduce the number of passes over the data to build the histograms by populating both at once
2. If the maximum element in the data has an empty high byte, skip one level of the sort
I added a benchmark which varies the number of bits in the input data. On my branch (skylake 2.6GHz) I get 
```
Benchmark              (bits)  (seed)     (size)  Mode  Cnt  Score   Error  Units
RadixSort.partialSort      23       0  100000000  avgt    5  0.507 ▒ 0.011   s/op
RadixSort.partialSort      25       0  100000000  avgt    5  0.600 ▒ 0.016   s/op
```
On master I get 
```
Benchmark              (bits)  (seed)     (size)  Mode  Cnt  Score   Error  Units
RadixSort.partialSort      23       0  100000000 …
```

partial radix sort with early exit

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestIterators.java

The `forEach` method has a bug for when the run ends at `Integer.MAX` because of an overflow.

Verifies and fixes issue 475

---

RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapWriterRandomisedTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitSetUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestMemory.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestBitSetUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestMemory.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

We are relying in many places on unseeded random number generator which means that some of our tests may run over different data from run-to-run or from Java version to Java version. Though it has not caused harm, it is prudent to avoid this added complexity.

Less random testing.

---

RoaringBitmap/src/main/java/org/roaringbitmap/Container.java

The comment says OR but the operation is XOR, so fix that.

fix javadoc comment to be name the correct operation happening.

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/LongUtils.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

We were wanting a Flip range operation, so copied the existing "could be improved" operation used in the 32 bit implementation.
Added a few helper functions to work around change from int for the high word, to byte[].
Added unit tests to cover the cases I could think of while developing.
As a side note question if there is a way to get an enumerable range from the ART then the algorithm can be transposed to stepping over the existing containers in the range, and injected the gaps, and altering the existing nodes. This would remove the polling/search of every node in the range.

Add Flip ranger operation to Roaring64Bitmap

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

While reviewing Larsk-db PR #489 I noticed the adanceIfNeeded on the iterators was doing a signed compare instead of unsigned as needed.
So here is some tests (for forward/reverse iterators) to show this and a fix.

Roaring64 Iterators should treat advance values as unsigned long

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/502
The problem was that we were trying to match the key using the range [dep, node.prefixLength). The end index should instead be an offset calculated starting from dep i.e dep + node.prefixLength. 
The existing code just happened to work at the first depth, but gives incorrect results at depths > 0.
In my test i've constructed a case using data i've found that reproduces the result, but this can probably be made better using a generic construction which has a deep tree. 
I'm not sure how to do that, let me know what you think.

[Roaring64Bitmap] Fix index offset calculation when removing a key from the ART.

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Node48.java
RoaringBitmap/src/test/java/org/roaringbitmap/art/Node48Test.java

- This adds a test case, which reproduces #504 
- Add a fix for the bug
It turns out this has nothing to do with the iterator seek code whatsoever, but it actually an ancient bug in `Node48.getNextSmallerPos`. It couldn't handle the case where `pos=0`. The `pos--;` before the loop would decrement it to `pos=-1`, which we would then right-shift to `i=536870911`. That's clearly not a legal index into a 48-value array.
Now this issue by itself an easy fix, but I have another concern about `Node48` implementation that I'd like some feedback on (I could fix both at the same time, ideally):
I feel like `Node48` is breaking an implicit contract that functions like `getChildPos`, `getNearestChildPos`, `getNextLargerPos`, `getNextLowerPos` should return a concrete position within `children`, not a …

Fix Node48.getNextSmallerPos to handle input of 0 correctly

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java

change the max depth of `AbstractShuttle` from 6 to 7. The reason is though the max key length is 6 (6* 8 byte = high 48 bytes), but the `stack` member var still hold a  leaf node. So the max depth should be 7.
- If your pull request includes new functionality, then you must have corresponding new tests.

change the max depth from 6 to 7

---

RoaringBitmap/src/main/java/org/roaringbitmap/Container.java

Symbols such as `<` should not be used in comments unescaped as they cause problems with javadoc.

Some javadoc fixes

---

README.md
RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java
jmh/build.gradle.kts
jmh/src/jmh/java/org/roaringbitmap/rangebitmap/RangeBitmapBenchmark.java

This is a data structure for range indexes (index things like time, normalised floating point numbers etc.). 
Example usage:
```java
// index times before 13:00 UTC tomorrow
var appender = RangeBitmap.appender(LocalDateTime.of(2021, 9, 3, 13, 0, 0, 0).toInstant(ZoneOffset.UTC).getEpochSecond());
timestamps.forEach(appender::add);
RangeBitmap bitmap = appender.build();
RoaringBitmap beforeNow = bitmap.lessThanOrEqualTo(LocalDateTime.now().toEpochSecond(UTC));
```
There are significant advantages to implementing within the library as opposed to using the API:
```
Benchmark                                                                    (distribution)     (max)  (seed)  Mode  Cnt        Score         Error   Units
RangeBitmapBenchmark.rangeBitmap …
```

range bitmap

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Fixes some bugs (one by specification) around very large values, and adds a test case for encoded floating point numbers.

fix boundary bugs, add test for floating point use case

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java
jmh/src/jmh/java/org/roaringbitmap/rangebitmap/RangeBitmapBenchmark.java

This allows range queries intersected with another bitmap. For implementing double-ended range evaluations, the improvement is modest, but this is useful for speeding up range evaluations which will later be intersected with a bitmap.
```
Benchmark                                                       (distribution)    (rows)  (seed)  Mode  Cnt     Score     Error  Units
RangeBitmapBenchmark.rangeBitmap                             NORMAL(100000,10)  10000000      42  avgt    5    11.776 ±   0.233  us/op
RangeBitmapBenchmark.rangeBitmap                             UNIFORM(0,100000)  10000000      42  avgt    5  1997.871 ±  51.194  us/op
RangeBitmapBenchmark.rangeBitmap                      UNIFORM(1000000,1100000)  10000000      42  avgt    5  2491.862 ± 114.749  us/op …
```

contextual evaluation of ranges

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

`RangeBitmap` rounds the number of slices up to the nearest multiple of 8 because the masks need to be byte-aligned, but this is wasteful unless the required number of slices is a multiple of 8:
```
Benchmark                                   (distribution)    (rows)  (seed)  Mode  Cnt     Score     Error  Units
RangeBitmapBenchmark.rangeBitmap         NORMAL(100000,10)  10000000      42  avgt    5    14.507 ±   0.277  us/op
RangeBitmapBenchmark.rangeBitmap         UNIFORM(0,100000)  10000000      42  avgt    5  2180.766 ± 255.822  us/op
RangeBitmapBenchmark.rangeBitmap  UNIFORM(1000000,1100000)  10000000      42  avgt    5  2757.176 ±  90.761  us/op
RangeBitmapBenchmark.rangeBitmap               EXP(0.0001)  10000000      42  avgt    5  2196.845 ± 141.770  us/op
```
required number of …

don't round up number of slices

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

fix the 64bitmap and [issue](https://github.com/RoaringBitmap/RoaringBitmap/issues/537) when the and operation result has an empty container
To the Roaring64bitmap and() operation, it does not remove the empty container while does the and operation now. This
will result in memory waste and an not cleaned empty art state (currently we depend on the root node to be null to indicate that the art is empty, but the issue will make the art with an not null root node which has an empty container).
The fix is to remove the empty container when does the and operation.
-  I have run `./gradlew test` and made sure that my PR does not break any unit test.
-  I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

fix issue_537

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
jmh/src/jmh/java/org/roaringbitmap/aggregation/and/BitmapContainerAndBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/aggregation/or/BitmapContainerOrBenchmark.java

Speed up `ior`:
before
```
Benchmark                              (thatDensity)  (thisDensity)  Mode  Cnt     Score    Error  Units
BitmapContainerOrBenchmark.stable                0.1            0.1  avgt    5  1022.169 ± 42.764  ns/op
BitmapContainerOrBenchmark.stable                0.1            0.5  avgt    5  1023.257 ± 63.641  ns/op
BitmapContainerOrBenchmark.stable                0.5            0.1  avgt    5  1016.649 ± 41.469  ns/op
BitmapContainerOrBenchmark.stable                0.5            0.5  avgt    5  1020.667 ± 66.231  ns/op
BitmapContainerOrBenchmark.tendToZero            0.1            0.1  avgt    5   411.551 ± 13.539  ns/op
BitmapContainerOrBenchmark.tendToZero            0.1            0.5  avgt    5   410.931 ± 21.078  ns/op
BitmapContainerOrBenchmark.tendToZero …
```

ior fission + benchmark to show iand fission is unprofitable

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java

Strictly speaking, our bitmaps violate the Java contract. It is possible for two bitmaps to be "equal" while having a different hash code.
The reason why that is is that...
1. We decided that equals was "set equality". So it is not sensitive to runOptimize(). It makes sense, I suppose. It can be computed quickly. We have fast algorithms.
2. For the hashCode computation, if we want to it to be insensitive to the runOptimize(), we effectively have to redo the run compression, it seems and I cannot find an efficient way to do it. Now, if we only had arrays and run containers, it would not be too hard. You could hash a run like this... 
```Python
def fast(start, end):
K = end + 1 - start
return ((31**K-1)*(30*start+1)-30*K) // 900
```
and it would be equivalent to the array computation …

Improving documentation.

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java
jmh/src/jmh/java/org/roaringbitmap/rangebitmap/RangeBitmapBenchmark.java

Allows {i : a <= x_i <= b} to be computed on a `RangeBitmap` in one pass, which is a little faster than the current API allows.
```
Benchmark                                                            (distribution)    (size)  Mode  Cnt          Score     Error  Units
RangeEvaluationBenchmark.rangeBitmap                                       EXP(0.5)  10000000  avgt    5       1876.066 ±  42.245  us/op
RangeEvaluationBenchmark.rangeBitmap:cardinality                           EXP(0.5)  10000000  avgt    5   37758060.000                #
RangeEvaluationBenchmark.rangeBitmap:rows                                  EXP(0.5)  10000000  avgt    5   11933890.000                #
RangeEvaluationBenchmark.rangeBitmap:serializedSize                        EXP(0.5)  10000000  avgt    5   22406230.000 …
```

One pass range between

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

1. the mask would empty when only the value 1 is encountered during building, so a dirty flag is required when values are appended
2. if there's only one slice, and it's empty, the mask for the last container-region could overflow the end of the bitmap, so it needs to be chosen read more cautiously
3. between wasn't setting up the first slice when there are no containers properly

RangeBitmap fixes when the value 1 is the only value added to a range

---

RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Issue https://github.com/RoaringBitmap/RoaringBitmap/issues/558 suggests that removing values at random from a Roaring64Bitmap object could lead to errors. We attempt to verify.
Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/558

Trying to add and remove values from a Roaring64Bitmap

---

RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

It adds the following test...
```Java
public void testIssue566() {
RoaringBitmap roaringBitMap = new RoaringBitmap();
BitSet bitSet = new BitSet(5000);
double prob = 0.001;
Random random = new Random();
for (int i = 0; i < 5000; i++) {
if (random.nextDouble() < prob) {
bitSet.set(i);
roaringBitMap.add(i);
}
}
long roaringbits = roaringBitMap.getSizeInBytes() * 8;
long bitsetbits = bitSet.size();
System.out.println("[issue566] cardinality: "+ roaringBitMap.getCardinality());
System.out.println("[issue566] bitset bits: "+ bitsetbits);
System.out.println("[issue566] bitset bits per entry: " + bitsetbits * 1.0 / bitSet.cardinality());
System.out.println("[issue566] RoaringBitmap bits: " + roaringbits);
System.out.println("[issue566] RoaringBitmap bits per entry: " + roaringbits * 1.0 / …
```

Verifies issue 566.

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

Currently the iterator can return true for `hasNext` after the last batch, before returning no data, after returning no data, `hasNext` returns false. This change simplifies the code and avoids this last pointless iteration.

simplify BatchIterators, fix bug in advanceIfNeeded

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/CloneBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/CloneBatchIteratorTest.java

Remove shared references in clone of RoaringBatchIterator

---

build.gradle.kts

Instead of building a `/` separated filesystem path as a string, use `Path#resolve`, which should use the host system's separator.
Should fix https://github.com/RoaringBitmap/RoaringBitmap/issues/571, but I do not have a Windows system to test on. 
(note that `./gradlew check` should do both of those)

Use Path to assemble the local debug repo URI to hopefully be Windows compatible

---

jmh/build.gradle.kts
jmh/src/jmh/java/org/roaringbitmap/realdata/wrapper/BitmapFactory.java
jmh/src/jmh/java/org/roaringbitmap/realdata/wrapper/ConciseSetIteratorWrapper.java
jmh/src/jmh/java/org/roaringbitmap/realdata/wrapper/ConciseSetWrapper.java
jmh/src/jmh/java/org/roaringbitmap/realdata/wrapper/ImmutableConciseSetWrapper.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/AllRunHorizontalOrBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/RunArrayAndBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/RunArrayAndNotBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/RunArrayOrBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/RunArrayXorBenchmark.java

The version of extendedset used in the benchmarks no longer exists, but the code was maintained by the Apache Druid project for several years and is available on Maven Central. This change may prevent the results used in papers from being reproducible, but that's because the library tested against doesn't exist any more.

Extendedset renovation

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/BackwardShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/ForwardShuttle.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

- Added test cases for the issues described in #577 
- Fixed a signed byte comparison that should have been unsigned in the two shuttle implementations of the trie.
This fixes #577

Roaring64Bitmap.forInRange correctness issues

---

build.gradle.kts

- This removes unneeded plugins that serve to compute our test coverage. We don't actually use these metrics in practice.

We don't actually rely on automated coverage metrics.

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Fix RangeBitmap issue when all slices should be skipped

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

In-place operation with the bitmap itself are not currently guarded.
Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/592

Guarding the case where someone does an in-place operation with the bitmap itself

---

.github/workflows/java8.yml
RoaringBitmap/build.gradle.kts
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/LongUtils.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestLongUtils.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

- Multiple fixes related to Roaring64NavigableMap.addRange, specific to high being bigger than Long.MAX_VALUE
- Add tests to confirm same behavior between Roaring64NavigableMap and Roaring64Bitmap
- Add Roaring64NavigableMap.addRange, to prevent confusion between Roaring64NavigableMap.add(long, long) and Roaring64NavigableMap.add(long...). Same for Roaring64Bitmap

Fix add range around -1L in Roaring64NavigableMap and Roaring64Bitmap

---

RoaringBitmap/build.gradle.kts
RoaringBitmap/src/main/java/org/roaringbitmap/art/Containers.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/ImmutableLongBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/LongBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/JolBenchmarksTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

- Copy and extends footprint benchmarks from #346
- Simplify and refactor tests for . serializedSizeInBytes

Add fallback for Roaring64Bitmap.getLongSizeAsBytes(), and introduced footprint benchmarks for 64b

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestForAllInRange.java

- The `forAllInRange` implementation in `RoaringBitmap` was treating unsigned integers wrong.
- Added a bunch of parametrised tests to reproduce the issue. (Conveniently the range consumer being relative, makes it easy to write tests using offsets.)
- Changed all variable naming in the `forAllInRange` implementation such that vars that must be treated as unsigned always start with a `u`.
- Fixed all the places where unsigned ints were compared as signed.
- Also some more comments, assertions, and code cleanup to make this implementation easier to read/review.

Bugfixes for forAllInRange with large integers.

---

README.md
RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Adds `RangeBitmap.eq`, `RangeBitmap.eqCardinality`, `RangeBitmap.neq` and `RangeBitmap.neqCardinality`. These methods allow `RangeBitmap` to be used as a kind of compact inverted index which trades space for time.

add RangeBitmap.eq and RangeBitmap.neq

---

RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java

When using `naive_and` aggregation, putting a tiny bitmap first can be beneficial. Let us communication this insight to the users.
Related to https://github.com/RoaringBitmap/RoaringBitmap/issues/608

Added a performance hint.

---

RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java

This is based on observations made in Apache Pinot and separately in #608 
* for small numbers of bitmaps, naive_and can be faster than the more complex workShyAnd method
* putting the smallest bitmap first in the aggregation can accelerate intersections

clone smallest bitmap, adjust naive/workshy and thresholds in `FastAggregation.and`

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

- The initial insert method of the Art does not consider a case that the leaf node was shrunk from some other node types, and just assume it is a fresh leaf node. That's wrong. So we add the logic to reset the leaf node's prefix information while inserting.

reset the prefix of the leaf node while inserting

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringArray.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestSerialization.java

- the result of block nums is wrong,  for example, `iBlock <=  bitmapArray.length / buffer.length / 8` should be `iBlock <= 8 * bitmapArray.length / buffer.length `,   or else,  the unit tests related to *roaringbitmap serialization* are failed.

fix RoaringArray deserialize(DataInput in, byte[] buffer) bug

---

.github/workflows/checkascii.yml
.github/workflows/java11.yml
.github/workflows/java17.yml
.github/workflows/java8.yml
.github/workflows/macos.yml

Update GitHub Actions to versions using supported versions of NodeJS, see https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
No: No changes to any Java or build files.

Update actions to run on Node16

---

bsi/src/main/java/org/roaringbitmap/bsi/BitmapSliceIndex.java
bsi/src/main/java/org/roaringbitmap/bsi/RoaringBitmapSliceIndex.java
bsi/src/main/java/org/roaringbitmap/bsi/buffer/BitSliceIndexBase.java
bsi/src/main/java/org/roaringbitmap/bsi/buffer/ImmutableBitSliceIndex.java
bsi/src/main/java/org/roaringbitmap/bsi/buffer/MutableBitSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/BufferBSITest.java
bsi/src/test/java/org/roaringbitmap/bsi/RBBsiTest.java

This PR fixes the bug when BSI using the max value for evaluation, currently BSI uses below logic  in comparing: https://github.com/RoaringBitmap/RoaringBitmap/blob/d9d0914ea78d0b25fb5813159a0a1230d701b5ee/bsi/src/main/java/org/roaringbitmap/bsi/RoaringBitmapSliceIndex.java#L410-L415
which is not correct. For example, when the operation is `NEQ` or `LE`,  if the `startOrValue` is greater than the `maxValue`, the return should not be an empty set, but the full set of all values.
To fix this, this add a `compareUsingMinMax` method to deal with different operations. This also fixes the bug that the min value and the max value are not updated after the `add` operation,  this recalculate and update min and max values after each …

Fix bug when BSI uses min max values for evaluation and some other improvements

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
jmh/src/jmh/java/org/roaringbitmap/runcontainer/GetCardinalityMappeableContainerBenchmark.java

Only up to 10% more performant `MappeableRunContainer.getCardinality()`, analogously improved `RunContainer.getCardinality()`, but as it is basic functionality, it should be worthy still. Benchmark provided.
Off topic question: Isn't more correct naming "Mappable" instead of used "Mapp**e**able"? I know, this breaks backward API compatibility, but it can be done when new major version will be released (1.0).

Optimized getCardinality() for (Mappeable)RunContainer

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/insights/NaiveWriterRecommender.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java

There are used two ways to increase the performance of String creation:
1. Use `StringBuilder.append(char)` instead of `StringBuilder.append(String)`. The first one is more performant even for several chars, not only for one.
2. Allocation sufficient space for `StringBuilder` instance as this avoids backed char array repeated initialization (and copy).

More performant toString() methods

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/IntegerUtil.java
jmh/src/jmh/java/org/roaringbitmap/longlong/ShiftLeftFromSpecifiedPositionBenchmark.java

Test for changed method `IntegerUtil.shiftLeftFromSpecifiedPosition()` already existed - `IntegerUtilTest.testShiftLeftFromSpecifiedPosition()`.
Simple comparison benchmark `ShiftLeftFromSpecifiedPositionBenchmark` also created, I suppose it should be removed after verification and before merge.

More performant integer shift left by bytes

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java
jmh/src/jmh/java/org/roaringbitmap/IntermediateByteArrayBenchmark.java

Tiny performance improvement for `Node16.insert()` operation, see created benchmark.

Avoid intermediate byte array creation

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

- Fix issue reported in https://github.com/RoaringBitmap/RoaringBitmap/issues/646

646 - Fix  `.andNotCardinality`

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitSetUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferBitSetUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitSetUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestBitSetUtil.java
jmh/src/jmh/java/org/roaringbitmap/BitSetUtilBenchmark.java

- There is no direct way to convert a byte array or a ByteBuffer (representing an uncompressed bitmap) to a RoaringBitmap 
- The best way is to create a BitSet first and then use: BitSetUtil.bitmapOf(bitset)
- This creates unnecessary heap garbage as, essentially, a full copy of the byte array is created for BitSet
- This PR introduces a method in BitSetUtil that can be used to directly convert a ByteBuffer to RoaringBitmap
- The implementation tries to do it with constant and minimum possible memory allocation
- This is very useful for performance sensitive code doing this very frequently. Now a RoaringBitmap can be created directly from bytes read on wire with almost no unnecessary memory allocs
- For testing, BitSetUtil tests are replicated and benchmarks are added
- Benchmark Results …

Optimisation: Add zero-garbage deserialiser for ByteBuffer to RoaringBitmap

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestSerialization.java

Issue https://github.com/RoaringBitmap/RoaringBitmap/issues/652 describes a verifiable problem where the intersects function fails. But it seems to fail only after deserialization (or, at least, that's the reproducible test case we have). In PR https://github.com/RoaringBitmap/RoaringBitmap/pull/653, @shanielh proposes to change the deserialization process, seemingly increasing the initial capacity after deserialization. That's fine, but I don't think that's where the actual bug lies. The actual bug is a logical bug in `intersects` (one of our implementations).

This fixes a logical error in one implementation of 'intersects'

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java

Parts of code replaced by call to method `andCardinality()`, thus duplicated code is removed.

Use already existing routine andCardinality() to avoid code duplication

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java

Binary search limited to search from known minimal possible start index. This reduces its number of steps.

Binary search on part of array only

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java

More effective buffer copying when limiting direct array container.

more effective buffer copying when limiting mappable container

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java

Computation skips of shifted containers that would be discarded due to out of bounds keys in the case of container unaligned offsets. This solves #544.

AddOffset optimization

---

RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

In issue https://github.com/RoaringBitmap/RoaringBitmap/pull/666, @xtonik reported an issue where flipping a value in an array container would lead to the wrong result. However, they did not provide an actual test using our public API.
To try to determine whether the issue is real, I added tests based on their unit tests.

Trying to verify issue with flips.

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestReverseIteratorsOfContainers.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestIntIteratorFlyweight.java
jmh/src/jmh/java/org/roaringbitmap/AdvanceIfNeededBenchmark.java

Action `advanceIfNeeded()` on bitmap container was not optimal as noted in source code - too complicated bit-wise iterating within one long value, where given limit value belongs to. Above that, when this long value (64-bit bitmap) is not zero and no value under / above limit was found, iterating is done by bits, not by bitmap longs as probably supposed by author of code.
Temporary performance comparison can be seen by running `AdvanceIfNeededBenchmark` when 48ac7f9 is checked out. According to my tests, 10% performance improvement reached.
Tiny related code cleanup done also.

AdvanceIfNeeded on bitmap container optimized

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/RunBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

Added unit test to expose batchiterator.advanceIfNeeded bug

unit test to expose batchiterator.advanceIfNeeded bug and fix

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java

Added unit test to expose batchiterator.advanceIfNeeded bug (this time in the RoaringBitmap and fix it.

Fix roaringbitmap - batchiterator's advanceIfNeeded to handle run lengths of zero

---

RoaringBitmap/src/main/java/org/roaringbitmap/Util.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
jmh/src/jmh/java/org/roaringbitmap/AddOffsetBenchmark.java

`AddOffset()` optimized for array containers via avoidance of condition in a loop for filling values to containers. The index of split container is determined beforehand and thus the loop for filling values to first and next container is done separately. See benchmark results (less is better):
| Benchmark               | (scenario)                | Mode | Cnt | Score     | Error      | Units |
|-------------------------|---------------------------|------|-----|-----------|------------|-------|
| optimized               | ARRAY_ALL_IN_LOW          | avgt | 5   | **8819.802**  | ± 1726.774 | ns/op |
| optimized               | ARRAY_HALF_TO_HALF        | avgt | 5   | **8632.215**  | ± 1556.700 | ns/op |
| optimized               | ARRAY_ALL_SHIFTED_TO_HIGH | avgt | 5   | **9889.661**  | ± …

AddOffset() optimization for array containers

---

RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

Changed the expression causing integer overflow in some tests, I suppose unintentional in most of cases. This will be not reported by static code analyzers at least.

Avoid integer overflow within tests

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java

Logical operators replaced by bitwise operators, where it should be. No visible performance improvement is reached, so static code analyzer will not complain about that at least.

Bitwise operator instead of logical

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
jmh/src/jmh/java/org/roaringbitmap/deserialization/BitmapContainersDeserializationBenchmark.java

Avoid to use constructors of `(Mappeable)BitmapContainer(int, LongBuffer)` , whose duplicates buffer of given bitmap first, then allocate new buffer, and copy duplicated buffer to newly created one - except the cases, where are called from method `clone()` of course. After these changes it is possible to copy part of buffer only, not copy whole buffer and then unset the rest.
| Benchmark – higher values are better | Mode  | Cnt | Score | Error   | Units  |
|--------------------------------------|-------|-----|-------|---------|--------|
| newly optimized                      | thrpt | 5   | 0.531 | ± 0.028 | ops/ms |
| original                             | thrpt | 5   | 0.301 | ± 0.048 | ops/ms |
Benchmark measurement for original implementation can be obtained after checkout [commit …

Avoid array reallocation

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
jmh/src/jmh/java/org/roaringbitmap/bitmapcontainer/SelectBenchmark.java

Performance optimization for action` (Mappeable)BitmapContainer.select(int)` - if bitmap container's cardinality is known beforehand, **decision is made if search loop should start from the beginning or from the end of the bitmap.** This should lead to double the performance in average when values within bitmap are uniformly distributed, this fact is verified by presented benchmark.
Above that, **counting bit are avoided for words equal to zero** even this occurs not so often as too sparse bitmaps are probably converted to other kind of container. Shortly it is useful, where huge part of bitmap is empty, but the cardinality is still above the conversion threshold.
| Benchmark                                | (valuesCount) | Mode  | Cnt | Score  | Error    | Units  | …

Select from both sides

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/Util.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

Methods `fillArray()` deduplicated, part for processing buffered input removed completely as it was dead code. This part also contained the bug - `numberOfLeadingZeros()` was used instead of correct `numberOfTrailingZeros()`.

Method fillArray() deduplicated

---

bsi/src/main/java/org/roaringbitmap/bsi/buffer/BitSliceIndexBase.java

Avoid useless computation in `oNeilCompare()` according to their necessity for processed operation.

Avoid useless computation in oNeilCompare()

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestUtil.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestUtil.java
jmh/src/jmh/java/org/roaringbitmap/BitmapOfRangeBenchmark.java

Optimized creation of bitmap by range via factory method `Util.bitmapOf()`. There is a trade-off between performance and  code is  duplication, but it can be ignored as piece of duplicated code is already duplicated several times in class `RoaringBitmap`.
| Benchmark | (offset) | (bytes) | Mode | Cnt | Score | Error | Units | 
| --- | --- | --- | --- | --- | --- | --- | --- |
| optimized | 0 | 10 | avgt | 5 | 31.364 | ±0.964 | ns/op |
| optimized | 0 | 100000 | avgt | 5 | 45.240 | ±3.783 | ns/op |
| optimized | 0 | 10000000 | avgt | 5 | 1663.824 | ±22.388 | ns/op |
| optimized | 100000 | 10 | avgt | 5 | 31.179 | ±0.358 | ns/op |
| optimized | 100000 | 100000 | avgt | 5 | 59.337 | ±9.726 | ns/op |
| optimized | 100000 | 10000000 | avgt | 5 | 1764.398 | ±329.763 | ns/op |
| original | 0 | …

Optimized creation of bitmap by range

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitSetUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitSetUtil.java

Add methods to allow direct conversion of a RoaringBitmap to a BitSet. This turned out to not be as simple as it first appeared, and the existing tests were a godsend.
This performs quite well too, I see over 5GB/s on my M1 MacBook Pro for 86,884 ops/s.
- [ x ] I have run `./gradlew test` and made sure that my PR does not break any unit test.
- [ x ] I have run `./gradlew checkstyleMain` or the equivalent and corrected the formatting warnings reported.

RoaringBitmap to BitSet/long[]/byte[]

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java

Related to https://github.com/RoaringBitmap/RoaringBitmap/pull/713, `RunContainer.getCardinality()` dominates CPU time in `toBitmapContainer`:
We can tally the cardinality as we iterate the runs.

Avoid getCardinality in RunContainer.toBitmapContainer

---

.github/workflows/java-all-versions.yml

As one of four LTS versions being supported by Eclipse Temurin (see https://adoptium.net/support/), add Java 21 as a tested version.  The next expected version to add is Java 25 on or after September 2025 and the next expected version to drop is Java 8 on or after Nov 2026.

ADD Java 21 to CI

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitSetUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/Container.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitSetUtil.java

Another quick follow up to #713 to avoid `toBitmapContainer` as this has shown up on hot paths for us too.

Avoid intermediate arrays for other container types

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestContainer.java

- Add the test mentioned in #717 
- Change `toBitmapIfNeeded` to `toEfficientContainer` at the end of `or` and `ior` for `RunContainer` and `MappeableRunContainer`.
- Remove the now unused `toBitmapIfNeeded` methods.
- This fixes #717

Fix for or:ing two RunContainers that produce an undersized BitmapContainer

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

The edge cases for nextAbsentValue and previousAbsentValue were undefined.

fix: formalize edge behaviour for nextAbsentValue and previousAbsentValue

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

Fixes #721: Advancing to the next run, because the current bit is beyond the end of the current run, should not also advance to the next bit.
Add new unit-tests to cover the cases mentioned and another to add coverage of a missed branch.

Fix RunContainer#contains(BitmapContainer) (#721)

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java

Fixes #723 off-by-one error in `ArrayContainer#contains(RunContainer)` call to `contains(int,int)`
Added new unit-test.
There's perhaps some potential for a micro-optimization since contains(int,int) immediately subtracts the 1 just added.

Fix ArrayContainer#contains(RunContainer) (#723)

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitSet.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitSetTest.java

Add a `BitSet` implementation based on RoaringBitmap to make users could migrate `BitSet` to `RoaringBitmap` easier.

[feature] Add a BitSet implementation based on RoaringBitmap

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestIterators.java

Add getSignedIntIterator to roaring bitmaps
We sometimes use roaring bitmaps for iterative filtering where the opposite side of the join is sorted using signed comparison. This adds a function for creating a peekable int iterator to more easily allow that. This is considerably more efficient and easier than implementing the sorted iterator on the client side.
Tests are added for both roaring bitmaps and immutable roaring bitmaps. As well, existing int iterator tests have been improved to use integers above 2^31 in the test iterators, which was missing by only taking the absolute value of the random integers.

add getSignedIntIterator to roaring bitmaps 

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestIterators.java

- Fixes advanceIfNeeded in signed int iterators 
Take into account sign bits while iterating over containers. Previously it would skip over positive signed integers after advancing to a negative signed integer. For signed int iterator this should work the oppositive way, positives come after negatives.
- Use advanceUntil to find starting container index in signed int iterators
This should find starting containers much faster, as it's using binary search instead of doing a sequential scan.

Fix advanceIfNeeded in signed int iterators and simplify finding starting container index

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

Recently came across this issue, while I was trying to find maximum signed integer using previousValue, where it would simply just return -1 (not found) in some cases (but not all). This first issue is only happening when target container is absent and a container exists with higher key.
While looking at the code, also noticed that last is not returned as unsigned long as promised by the api. This second issue is only happening when target container is absent and no container exists with higher key.
Both cases are covered with test cases.

Fix previousValue not returning correct results in some cases

---

RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

Discovered last week while running fuzz tests.
When an empty word is encountered, it takes the first value from the next bitset in the array.
This value can be smaller than the current range start resulting in incorrect result.
Example from unit tests:
```java
Container rc = new RunContainer().add(128, 512);
Container subset = new BitmapContainer().add(256, 320);
```
Since the first bitset is empty, it would look for 64 (0 * 64 + 64 trailing zeros), but our range starts at 128.
The issue can be also reproduced by running `intersectsContainsRemove` in fuzz-tests.

Skip over empty words in RunContainer#contains(BitmapContainer)

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/PointableRoaringArray.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

Proposal, following up on https://github.com/RoaringBitmap/RoaringBitmap/pull/736#issuecomment-2214234248
Adds firstSigned and lastSigned methods that return minimum signed and maximum signed integer in bitmap, respectively.
In java world, depending on the usage, we are often more interested in signed minimums and maximums.
The same thing can be achieved by combining nextValue/previousValue with last/first.
This just adds a cleaner and a slightly more efficient way to do it.
Not sure about the naming, if it's going to cause confusion. Open to suggestions.

Implement signed first/last methods

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/KeyIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/R64BSITest.java

- Add BSI based on Roaring64Bitmap so as to support (column id:bigint, value:bigint)

Add BSI based on Roaring64Bitmap

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

https://github.com/RoaringBitmap/RoaringBitmap/issues/611
This PR adds the getContainerCount() method as a public method in both RoaringBitmap and ImmutableRoaringBitmap classes. This method will provide users with the ability to retrieve the number of containers in a bitmap, which can be useful for understanding the internal structure and memory usage of the bitmap.
It will help pinot in some specific usecases : https://github.com/RoaringBitmap/RoaringBitmap/issues/608#issuecomment-1364722016

Changes for adding container size

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitSetUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/Util.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

Some pieces of code deduplication by introducing routine for bitmap keys intersection. Also some other code was deduplicated using existing routine `BitSetUtil.arrayContainerBufferOf()` .

Merging bitmap keys deduplicated

---

bsi/src/main/java/org/roaringbitmap/bsi/RoaringBitmapSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/RBBsiTest.java

Fix an issue that may cause RoaringBSI's fountSet to not work  ##correctly when doing LE and GE comparisons.
- A small change to [RoaringBitmapSliceIndex.java](https://github.com/RoaringBitmap/RoaringBitmap/compare/master...iszhangpch:fix-bsi-compare-issue?expand=1#diff-d48ea435f24454253ec7b2478435a8be06fe8848421e223ec0203c7797bd13bf)

Fix an issue that may cause RoaringBSI's fountSet to not work

---

roaringbitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

```
new Roaring64Bitmap().clone();
```
throws an exception.
PR fixes the issue.

[bugfix] Cloning empty Roaring64Bitmap now does not throw an exception.

---

bsi/src/main/java/org/roaringbitmap/bsi/buffer/BitSliceIndexBase.java
bsi/src/test/java/org/roaringbitmap/bsi/BufferBSITest.java

According to the [Bit-sliced index arithmetic](https://dl.acm.org/doi/10.1145/376284.375669), the topk if n too many rows in F, turn off n bits from E in F.

fix the bsi topk bug

---

bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java

This pull request resolves the issue mentioned in https://github.com/RoaringBitmap/RoaringBitmap/issues/764.

readVInt causes inability to deserialize long data

---

roaringbitmap/src/main/java/org/roaringbitmap/longlong/ImmutableLongBitmapDataProvider.java
roaringbitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Refs: #768
- added two new tests for iterator, stream and reverseIterator, reverseStream (the second triggers / demonstrates the bug)
- fixed the bug

fix: Roaring64Bitmap reverseStream produces increasing row of numbers

---

roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java

Fixes overflow in ImmutableRoaringBitmap#flip that occurs when range ends in the highest possible 16-bit key (65535) container.
This includes range ends from `(1L << 32) - (1 << 16)` to `(1L << 32)`
MutableRoaringBItmap doesn't have this issue, but included test for both.

Fix overflow in ImmutableRoaringBitmap#flip

---

roaringbitmap/src/main/java/org/roaringbitmap/art/Art.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node.java

dont create empty arrays, use a shared empty array
There was one broken test broken before I chnaged, and its unaffected ([TestSerializationViaByteBuffer](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html). [[14] 8, LITTLE_ENDIAN, true](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html#testDeserializeFromMappedFile(int,%20ByteOrder,%20boolean)%5B14%5D). I am running on windows
part of https://github.com/RoaringBitmap/RoaringBitmap/issues/776

share empty arrays

---

README.md
roaringbitmap/src/main/java/org/roaringbitmap/buffer/CopyOnWriteRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestCopyOnWrite.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestCopyOnWriteEdgeCases.java

**Copy-on-Write Implementation for Roaring Bitmap** 
**Overview** 
This document provides a comprehensive explanation of the copy-on-write (CoW) implementation for Roaring Bitmap, specifically addressing GitHub [issue #193.](https://github.com/RoaringBitmap/RoaringBitmap/issues/193) The implementation enables efficient conversion of memory-mapped Roaring Bitmaps to mutable bitmaps by sharing containers until modification is required. 
**What is Copy-on-Write?** 
Copy-on-Write is a resource management technique where multiple copies of data can share the same underlying storage until one of them needs to modify the data. At that point, a private copy is created for the modifier, while other references continue to share the original data. 
**Benefits** 
Memory Efficiency: Shared containers …

Implement copy on write roaring bitmaps

---

roaringbitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java

dont count and compare with 0
just see if any of the registers are non empty
There was one broken test broken before I changed, and its unaffected ([TestSerializationViaByteBuffer](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html). [[14] 8, LITTLE_ENDIAN, true](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html#testDeserializeFromMappedFile(int,%20ByteOrder,%20boolean)%5B14%5D). I am running on windows
Part of https://github.com/RoaringBitmap/RoaringBitmap/issues/776

make isEmpty faster

---

roaringbitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java

make isEmpty simpler and non mutating
related to https://github.com/RoaringBitmap/RoaringBitmap/issues/773
There was one broken test broken before I chnaged, and its unaffected ([TestSerializationViaByteBuffer](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html). [[14] 8, LITTLE_ENDIAN, true](https://github.com/RoaringBitmap/RoaringBitmap/compare/classes/org.roaringbitmap.buffer.TestSerializationViaByteBuffer.html#testDeserializeFromMappedFile(int,%20ByteOrder,%20boolean)[14]). I am running on windows

issue-773-don't mutate in isEmpty

---

roaringbitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
roaringbitmap/src/main/java/org/roaringbitmap/longlong/LongUtils.java

- reduce retained memory in LeafNode - make the key just 48 bits
- dont allocate byte[] to handle keys - just manipulate the bytes
just the normal windows failure that may be fixed with https://github.com/RoaringBitmap/RoaringBitmap/pull/781

reduce retained memory and allocations in LeafNode

---

roaringbitmap/src/main/java/org/roaringbitmap/art/Art.java
roaringbitmap/src/main/java/org/roaringbitmap/art/BranchNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node16.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node256.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node4.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node48.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node16Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node256Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node48Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node4Test.java

this reduces the retained memory of nodes (4 or 8 bytes per Mode)
- remove the field, as it can be derived from the class
- make some methods virtual

remove nodeType from Branch nodes (its hardly used)

---

roaringbitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Art.java
roaringbitmap/src/main/java/org/roaringbitmap/art/BranchNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node16.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node256.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node4.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node48.java

remove a minor memory leak
- remove `prefixLength`, as is should always be `prefix.length`
- expose a methos for the same functionallity
Note 
there was one case where the above wasn't true, (when an array wasn't being resized) which was a very small and bounded memory leak

remove `prefixLength` to save some memory.

---

roaringbitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node4.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node4Test.java

Node4 has a memory leak. The last node references is nulled
so if you have a node containing (a,b,c,d)
and then you remove(0), and remove (2)
The leak is caused by the fist remove, but only becomes a leaf on the second one
the node contains ((b,c), but the child array is (b,c,null, d)
I had a quick look at the higher order odes and they look OK, but need tests
I dont have time to write these now, and cant be sure of not similar leaf being there (or creeping in later), so I think there should be some tests to confirm this

fix memory leak in Node4.remove

---

jmh/src/jmh/java/org/roaringbitmap/longlong/AddRoaring64.java
jmh/src/jmh/java/org/roaringbitmap/longlong/BuildFromEmpty.java
jmh/src/jmh/java/org/roaringbitmap/longlong/FindRoaring64.java

followup to https://github.com/RoaringBitmap/RoaringBitmap/pull/797
I missed a commit :-(. added comments and then didnt push the updates cos I lost connectivity
from running
`java -jar jmh/build/libs/benchmarks.jar -f 1 -r2 -i 5 -w 2 -wi 2 'org.roaringbitmap.longlong.*' `
the values are not so interesting, but this shows the spread of parameters
```
Benchmark                                          (addedSize)  (count)  (initialSize)  (ordered)  (orderedAdd)  (pos)   (size)   Mode  Cnt          Score           Error  Units
AddRoaring64.AddExistingState.addAllExisting             10000      N/A          10000        N/A          true    N/A      N/A  thrpt    5       3932.510 ┬▒       136.842  ops/s
AddRoaring64.AddExistingState.addAllExisting             10000      N/A          10000 …
```

an few more benchmarks

---

roaringbitmap/src/main/java/org/roaringbitmap/art/Art.java
roaringbitmap/src/main/java/org/roaringbitmap/art/BranchNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node16.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node256.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node4.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node48.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node16Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node256Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node48Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node4Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/NodeCommon.java

- If your pull request includes new functionality, then you must have corresponding new tests. (TODO)
For the insert flow there are optimisations to be had by combining the `getChidPos` and `getChild` calls
In my (local) test this reduced the CPU usage by 13%
**Draft until we agree the API, and add tests**

calculate the Node at a key in a single step

---

jmh/src/jmh/java/org/roaringbitmap/longlong/CloneBenchmark.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Art.java
roaringbitmap/src/main/java/org/roaringbitmap/art/BranchNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Containers.java
roaringbitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node16.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node256.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node4.java
roaringbitmap/src/main/java/org/roaringbitmap/art/Node48.java
roaringbitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java

Improve clone implementation for Roaring64Bitmap
Add benchmark
I was seeing GC stats in non allocating code which was skewing some benchmarks on local code,. This noise was caused by the preceding `clone` in `setup`
I am unsure if additional unit tests are needed to ensure that clone is doing the right thing (i.e. no sharing of mutable structures etc
Perform a clone from the memory structure, rather than hydration
Summary comparison 
`clone` relates to the old implementation, `cloneNew` relates to the implementation in this PR
In all cases the new implementation used less CPU and produces less allocation. Full jmh table output in a comment below
```text
Benchmark                                          size)  Mode  Cnt          Score          Error   Units
CloneBenchmark.clone …
```

improve 64 bit clone

---

.github/workflows/gradle-wrapper-validation.yml

- The runner `gradle/wrapper-validation-action@v1` is obsolete. Replacing it with `gradle/actions/wrapper-validation@v3`.

update gradle wrapper validation

---

jmh/build.gradle.kts

just an uptick for a dependency (shadowjar), that has moved coordinates
No functionallity change. Just affect the building of the JMH component, which isnt production code, or unit test

update moved dependency
