RoaringBitmap/RoaringBitmap

src/main/java/org/roaringbitmap/IntIteratorFlyweight.java
src/main/java/org/roaringbitmap/ReverseIntIteratorFlyweight.java
src/test/java/org/roaringbitmap/TestIntIteratorFlyweight.java

This Iterator will let you go green and make your garbage collector suffer less.
*  Benchmark                                                      Mode    Samples    Score   Score error  Units
+ b.c.b.t.b.roaringBitmap.RoaringIteratorBenchmark.testFlyweight    thrpt      200  17347.182      102.962  ops/s
+ b.c.b.t.b.roaringBitmap.RoaringIteratorBenchmark.testStandard     thrpt      200  10302.179       53.562  ops/s

Flyweight primitive Iterator over a RoaringBitmap.

---

.gitignore
jmh/src/main/java/org/roaringbitmap/BasicBenchmark.java
jmh/src/main/java/org/roaringbitmap/iteration/IteratorsBenchmark.java

@lemire I have translated the benchmarks as-is . Please review them and if you merge, you can get rid of the old ones as well.

Benchmarks

---

jmh/pom.xml
jmh/run.bat
jmh/src/main/java/org/roaringbitmap/BasicBenchmark.java

Upgraded to the latest JMH (1.10.1) and added a SparseBitSet construction benchmark

Some (naive) SparseBitSet benchmarks for comparison

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java

fix for #53 ClassCastException on cloning ImmutableRoaringReverseIntIterator

---

eclipse-java-google-style.xml

I am adding only eclipse style sheet and skipped intellij style sheet since intellij can import eclipse stylesheet as well. 
Go ahead and merge it and reformat the entire code base. I could have reformatted but I din't want to show up as the largest contributor in this project :)

Adding checkstyle format code

---

src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Hi, this is my first pull request, I will try to keep adding test cases to improve the coverage. If you have some suggestion please tell me.
Sincerely,
Junyuan Zheng

Add test case to test unsignedIntersects() method

---

src/main/java/org/roaringbitmap/Util.java
src/main/java/org/roaringbitmap/buffer/BufferUtil.java
src/test/java/org/roaringbitmap/TestArrayContainer.java
src/test/java/org/roaringbitmap/TestIntIteratorFlyweight.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/TestUtil.java
src/test/java/org/roaringbitmap/buffer/TestFastAggregation.java
src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainerShortIterator.java
src/test/java/org/roaringbitmap/buffer/TestReverseMappeableRunContainer.java
src/test/java/org/roaringbitmap/buffer/TestRunContainer.java
src/test/java/org/roaringbitmap/buffer/TestUtil.java

Fix issue #101 , improve coverage to 80%

Fix issue #101, coverage improvement

---

src/main/java/org/roaringbitmap/RoaringBitmap.java
src/test/java/org/roaringbitmap/TestRange.java

Also fix tests of static versions of remove/add/flip to check the result of operations.

Fix the bug in member implementation of 'flip' (static version is fine)

---

jmh/src/main/java/org/roaringbitmap/RangeOperationBenchmark.java
pom.xml
src/main/java/org/roaringbitmap/BitmapContainer.java
src/main/java/org/roaringbitmap/RunContainer.java
src/main/java/org/roaringbitmap/Util.java
src/main/java/org/roaringbitmap/buffer/BufferUtil.java
src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
src/test/java/org/roaringbitmap/TestBitmapContainer.java
src/test/java/org/roaringbitmap/TestRangeCardinality.java
src/test/java/org/roaringbitmap/TestRunContainer.java
src/test/java/org/roaringbitmap/buffer/TestBufferRangeCardinality.java
src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
src/test/java/org/roaringbitmap/buffer/TestMappeableRunContainer.java

Range operations performance

---

src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestIterators.java

ImmutableBitmap was trying to reference 65k elements with a short value instead of using an int value ( as MutableBitmap does ).

wrong data type for pointer

---

src/main/java/org/roaringbitmap/RunContainer.java
src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

Fix RunContainer.andCardinality(RunContainer)

---

src/main/java/org/roaringbitmap/RoaringBitmap.java
src/main/java/org/roaringbitmap/RunContainer.java
src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
src/test/java/org/roaringbitmap/TestRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java
src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

This is a pull request in reference to the symmetric difference/xorCardinality part of #149. I added the left difference as andNotCardinality as well to be consistent with andCardinality and orCardinality.
This pull request depends on #154.

Xor cardinality

---

README.md

https://github.com/pilosa/pilosa

Add Pilosa as a library user

---

jmh/src/main/java/org/roaringbitmap/equals/EqualsBenchmark.java
jmh/src/main/java/org/roaringbitmap/runcontainer/BitmapToRuncontainerConversions.java
src/main/java/org/roaringbitmap/RunContainer.java
src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
src/test/java/org/roaringbitmap/TestRunContainer.java
src/test/java/org/roaringbitmap/buffer/TestMappeableRunContainer.java

There's no observable speed up in average speed, but the high centiles are improved significantly (on my laptop).

faster equals comparison run vs array #161

---

.travis.yml
pom.xml
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/OrderedWriter.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapSubsetTest.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferFuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/MutableRoaringBitmapSubsetTest.java

I upgraded to Java 8 and added some basic fuzz testing for various invariants against random bitmaps. This PR is here mostly to see the differential test coverage achieved, and in case anyone else has any opionions about randomised testing.

Fuzz testing

---

roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

just missing changes for buffered version

Trim() is not releasing all unused bytes

---

roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferParallelAggregation.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferParallelAggregationTest.java

This isn't necessarily for merge, just so @ppiotrow  and @maciej know it's here. This contains some of the improvements made to `ParallelAggregation` (copy and paste).

port various optimisations to the buffer package

---

roaringbitmap/src/main/java/org/roaringbitmap/ParallelAggregation.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferParallelAggregation.java

Small changes while getting familiar with the new Parallel executor.

Static instance of OR collector

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapIntervalIntersectionTest.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferFuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/RoaringBitmapIntervalIntersectionTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

Just knocked this up quickly. Let me know if there are obvious algorithmic improvements.

implement intersects with range

---

roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/BufferFuzzer.java

search and replace cardinality checks with emptiness checks

---

roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

* Checking buffer type after cloning MappeableBitmapContainer

Remove dead code (#137)

---

jmh/src/main/java/org/roaringbitmap/iteration/BatchIteratorBenchmark.java
pom.xml
roaringbitmap/src/main/java/org/roaringbitmap/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BatchIntIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/ContainerBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/RunBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ArrayBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BitmapBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RoaringBatchIterator.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/RunBatchIterator.java
roaringbitmap/src/test/java/org/roaringbitmap/CloneBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/RoaringBitmapBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/CloneBatchIteratorTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/ImmutableRoaringBitmapBatchIteratorTest.java

- make `BatchIterator` cloneable
- make it easily convertible to `IntIterator`

refine batch iterators 

---

shims/pom.xml
shims/src/main/java/org/roaringbitmap/ArraysShim.java
shims/src/main/java11/org/roaringbitmap/ArraysShim.java

Shims javadoc

---

shims/pom.xml
shims/src/main/java/org/roaringbitmap/ArraysShim.java
shims/src/main/java11/org/roaringbitmap/ArraysShim.java

Makes the shims module public, and it will have javadoc.

Public shims

---

fuzz-tests/src/test/java/org/roaringbitmap/BufferFuzzer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java
roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Container.java
roaringbitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Util.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

Closes #282 
I think my git "fixed" the line endings to all be '\n'. View the merge with `?w=1` to ignore the whitespace changes. I'm not sure how to fix this :S.

Implement next/previousAbsentValue

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Fix next/previousValue in ArrayContainer

---

roaringbitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/Util.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferUtil.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableBitmapContainer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java

This should complete the fix for issue 333

---

.travis.yml
fuzz-tests/src/test/java/org/roaringbitmap/BufferFuzzer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java
pom.xml
roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java

Added some fuzz tests for intersects with range and found a few more edge cases captured as unit tests.

Intersects range bugs

---

.travis.yml
README.md

Let us test with more JDKs.

---

RoaringBitmap/src/main/java/org/roaringbitmap/Container.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestArrayContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestBitmapContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestImmutableRoaringBitmapOrNot.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmapOrNot.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java
jmh/src/jmh/java/org/roaringbitmap/realdata/RealDataBenchmarkOrNot.java
jmh/src/jmh/java/org/roaringbitmap/realdata/state/RealDataRoaringBitmaps.java

1. In-place orNot through a member method
2. non in-place orNot through a class method

Implement RoaringBitmap.orNot operation #352

---

fuzz-tests/src/test/java/org/roaringbitmap/RandomisedTestData.java
jmh/src/jmh/java/org/roaringbitmap/RandomData.java

It seems that the random data generator for the fuzz tests was not generating run length encodable data when it claimed to be. I believe that this PR fixes that.

make sure random rle data will be run length compressed

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java

This is better documentation (no code change).

Clarifying rank and select

---

jmh/build.gradle.kts

I don't know what this does but it seems to please gradle somehow.

Doing what gradle asks for

---

RoaringBitmap/src/main/java/org/roaringbitmap/Container.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/OrNotTruncationTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBitmapIntervalIntersectionTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmapOrNot.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/RoaringBitmapIntervalIntersectionTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRunContainer.java
fuzz-tests/src/test/java/org/roaringbitmap/BufferFuzzer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java

adds some fuzz tests targeting `contains`, `intersects`, `remove` and fixes a few bugs.

more fuzz tests plus some fixes

---

RoaringBitmap/src/main/java/org/roaringbitmap/Container.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmapOrNot.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestImmutableRoaringBitmapOrNot.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestMappeableArrayContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

Makes the buffer package consistent. Should close #394.

Port ornot

---

RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestFastAggregation.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestFastAggregation.java
fuzz-tests/src/test/java/org/roaringbitmap/BufferFuzzer.java
fuzz-tests/src/test/java/org/roaringbitmap/Fuzzer.java
jmh/src/jmh/java/org/roaringbitmap/aggregation/FastAggregationRLEStressTest.java
jmh/src/jmh/java/org/roaringbitmap/realdata/ParallelAggregatorBenchmark.java

I am not sure that this is worth it. This is meant to address @kishoreg's concerns.

This is a version of Richard's function that uses *maybe* a bit less memory.

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestFastAggregation.java

to complete https://github.com/apache/druid/pull/9987

implement workshyand for iterator inputs

---

RoaringBitmap/build.gradle.kts
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
build.gradle.kts
jmh/build.gradle.kts
jmh/src/jmh/java/org/roaringbitmap/serialization/SerializationBenchmark.java
jmh/src/jmh/java/org/roaringbitmap/writer/WriteSequential.java
real-roaring-dataset/src/main/java/org/roaringbitmap/ZipRealDataRangeRetriever.java

This PR just removes a few annoying warnings. (No substantial change.)

More cleaning

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node256.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node48.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node16Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node256Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node48Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/Node4Test.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/428

fix the issue when iterating the ART interwove with the removing operations (#430)

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
shims/src/java11/java/org/roaringbitmap/ArraysShim.java

fix the issue 437 and related other ones.

fix the issue 437

---

RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Fixes #447 unit test. Test source doesn't reflect comments, this PR fixes that.

Fixes #447 Unit Test

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/BitmapBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBatchIterator.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunBatchIterator.java
RoaringBitmap/src/test/java/org/roaringbitmap/ContainerBatchIteratorTest.java
RoaringBitmap/src/test/java/org/roaringbitmap/RoaringBatchIteratorTest.java
jmh/src/jmh/java/org/roaringbitmap/iteration/ArrayBatchIteratorBenchmark.java

Hello, I gave It a try to implement advanceIfNeeded for batch iterator. Do you see It beneficial to merge these changes ? Feedback is very welcome

Implement advanceIfNeeded for batch iterator

---

real-roaring-dataset/src/main/java/org/roaringbitmap/ZipRealDataRetriever.java
simplebenchmark/src/main/java/simplebenchmark.java

Fixing the zip link the right way.

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/AbstractShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/BackwardShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/ForwardShuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node256.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node48.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/SearchResult.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Shuttle.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Fixes #488 .
@simeonpilgrim I hope you don't mind me verbatim copying your test cases here?

Fix advanceIfNeeded into gaps for Roaring64Bitmap

---

RoaringBitmap/src/test/java/org/roaringbitmap/longlong/ArtTest.java

After PR#489 lands, this will add some more tests, to show the seek behaviour is captured.

Add tests to check the seek behaviour of leafNodeIterator for post PR#489 merge

---

RoaringBitmap/src/main/java/org/roaringbitmap/FastRankRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap_FastRank.java

Fix issues #498 #499

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java

It's possible to cheaply calculate whether the running state will be cleared, so all work up until it would be cleared can be skipped. This allows to get out of some of evaluations very quickly:
```
Benchmark                                      (distribution)    (rows)  (seed)  Mode  Cnt      Score     Error  Units
RangeBitmapBenchmark.bsi                    NORMAL(100000,10)  10000000      42  avgt    5   1384.551 ±  34.284  us/op
RangeBitmapBenchmark.bsi                    UNIFORM(0,100000)  10000000      42  avgt    5  13565.476 ± 435.829  us/op
RangeBitmapBenchmark.bsi             UNIFORM(1000000,1100000)  10000000      42  avgt    5   1362.525 ± 135.940  us/op
RangeBitmapBenchmark.bsi                          EXP(0.0001)  10000000      42  avgt    5   3140.714 ±  70.624  us/op …
```

skip work when it can be determined the bitmap would later be cleared

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Another bug in `RangeBitmap` 😿

Rangebitmap serde bug

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java

This showed up in a profile querying inverted indexes in pinot, not a lot can be done about this but this PR makes some small improvements.

ImmutableRoaringArray construction micro-optimisations

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
jmh/src/jmh/java/org/roaringbitmap/aggregation/xor/BitmapContainerXorBenchmark.java

ixor optimisation

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Computes the count in a range without materialising a bitmap.

count ranges

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestRoaringBitmap.java

fix previousValue value smaller than first value

---

README.md

- When reading the README, I noticed a typo which I'm fixing through this PR.
**Note**: I suppose the below aren't necessary for this change. Let me know if I'm wrong.

Fix a typo in a sentence in the README

---

RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java

Adding a test for issue 580

---

RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Fix for issue 588 (bug in 'intersects').

Fix for issue 588

---

RoaringBitmap/src/main/java/org/roaringbitmap/ImmutableBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Art.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/ImmutableLongBitmapDataProvider.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/LongUtils.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

- Introduce .first and .last to 64 implementation
- If your pull request includes new functionality, then you must have corresponding new tests.

Introduce .first and .last to 64 implementation #583

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64NavigableMap.java
RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64NavigableMap.java

Clean prevent occurence of https://github.com/RoaringBitmap/RoaringBitmap/issues/563

Add transient to Roaring64NavigableMap.java.supplier #563

---

README.md

- If your pull request includes new functionality, then you must have corresponding new tests.

Update README.md: Adds SirixDB

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/Container.java
RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/LongUtils.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestForAllInRange.java

- Added individual container test cases for the 4 methods that are called by `RoaringBitmap.forAllInRange`
- Fixed all the bugs I found with those.
- Added more test cases for `RoaringBitmap.forAllInRange` and fixed all the bugs I found in those.

ForAllInRange Fixes Yet Again

---

README.md

Some trivial spelling/grammar corrections to the README.
I have not run any automated checks as it's just a README change.

Minor spelling correction to README

---

README.md

https://github.com/apache/iceberg/blob/d04efee702fcdcdbe3659c12f7442f5000aa246a/core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java#L24
- If your pull request includes new functionality, then you must have corresponding new tests.
- We require all Java files to be ASCII-only to avoid compatibility problems.

Add Iceberg to the list

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java

Method replacement with more specialized and more performant one.

More specialized method for value decrementation

---

RoaringBitmap/src/main/java/org/roaringbitmap/art/Node.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node16.java
RoaringBitmap/src/main/java/org/roaringbitmap/art/Node4.java

Simple duplicated code removal.

Duplicated small array sort routine

---

RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

Unnecessary comments as mentioned part of code is already optimal.

already optimal mappable array constructors

---

RoaringBitmap/src/main/java/org/roaringbitmap/FastAggregation.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/BufferFastAggregation.java

At https://github.com/RoaringBitmap/RoaringBitmap/pull/671#discussion_r1377281364, @richardstartin explains some code that appears to be unnecessary as an optimization. This PR adds comments so that we know why it is there.

Documenting GC optimization

---

RoaringBitmap/src/main/java/org/roaringbitmap/ArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/RunContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableArrayContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableRunContainer.java
RoaringBitmap/src/test/java/org/roaringbitmap/TestRunContainer.java

Counting new capacity of RunContainer was unified and a lots of code was deduplicated.

Counting new capacity of RunContainer unified

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java

Nothing else than application of known math identity `not(a) and not(b) <=> not(a or b)`.

One bitwise negation less

---

RoaringBitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
RoaringBitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Creation of range mask simplified. As I expect no visible performance gain is reached, the purpose of this change is to improve code readability. Tests were created to be sure not to break code functionality even the change is simple.

Creation of range mask simplified

---

RoaringBitmap/src/main/java/org/roaringbitmap/BitmapContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/buffer/MappeableBitmapContainer.java

Extension of https://github.com/RoaringBitmap/RoaringBitmap/pull/714 which includes mappeable container.

Move instance field to static, everywhere

---

RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java
RoaringBitmap/src/test/java/org/roaringbitmap/buffer/TestIterators.java

There is no bug but I wanted slightly more edge-case testing.

fix: add a few additional small tests

---

bsi/src/main/java/org/roaringbitmap/bsi/buffer/BitSliceIndexBase.java
bsi/src/test/java/org/roaringbitmap/bsi/BufferBSITest.java

You should not be mutating a bitmap while iterating over it.
Fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/745

fix for issue 745

---

RoaringBitmap/src/main/java/org/roaringbitmap/longlong/HighLowContainer.java
RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java
bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/R64BSITest.java
bsi/src/test/java/org/roaringbitmap/bsi/RBBsiTest.java

fixes https://github.com/RoaringBitmap/RoaringBitmap/issues/743

fix issue 743

---

bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/R64BSITest.java

fix issue 755

---

bsi/src/main/java/org/roaringbitmap/bsi/RoaringBitmapSliceIndex.java
bsi/src/main/java/org/roaringbitmap/bsi/buffer/BitSliceIndexBase.java
bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java
bsi/src/test/java/org/roaringbitmap/bsi/R64BSITest.java
bsi/src/test/java/org/roaringbitmap/bsi/RBBsiTest.java

fix issue 753

---

roaringbitmap/src/main/java/org/roaringbitmap/RangeBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/RangeBitmapTest.java

Adds an overload `RangeBitmap.between(long min, long max, RoaringBitmap context)` to `RangeBitmap.between(long min, long max)` to accept a context bitmap to be intersected with, consistently with other overloads. This allows intersection with another bitmap to be pushed down into the range evaluation, allowing much of the `RangeBitmap` to be skipped over.
This also uncovered a bug in the existing `betweenCardinality(long min, long max, RoaringBitmap context)` which has been fixed.

RangeBitmap between with context

---

roaringbitmap/src/test/java/org/roaringbitmap/TestSerializationViaByteBuffer.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/TestSerializationViaByteBuffer.java

- rework of https://github.com/RoaringBitmap/RoaringBitmap/pull/781 - looks like it does work properly
- let java remove the fixes, not junit

Fix windows delete take 2

---

roaringbitmap/src/test/java/org/roaringbitmap/art/Node16Test.java
roaringbitmap/src/test/java/org/roaringbitmap/art/Node4Test.java

- use assertEquals
- remove unused variable

minor changes to some tests

---

roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java
roaringbitmap/src/main/java/org/roaringbitmap/buffer/MutableRoaringBitmap.java
roaringbitmap/src/test/java/org/roaringbitmap/CheckedRemoveTest.java
roaringbitmap/src/test/java/org/roaringbitmap/buffer/CheckedRemoveTest.java

Fixing https://github.com/RoaringBitmap/RoaringBitmap/issues/801

fixing issue 801

---

bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64BitmapSliceIndex.java
bsi/src/main/java/org/roaringbitmap/bsi/longlong/Roaring64NavigableMapSliceIndex.java

saw some minor optimisations while looking at serialisation code for another PR

minor optimisations in 64 bit bit-slices
